###
#add post
POST http://localhost:3000/post
Content-Type: application/json

{
  "content": "This is the content of the sample post.",
  "senderId": "12335"
}

###
# Get All Posts
GET http://localhost:3000/post

###
#Get Posts by Sender
GET http://localhost:3000/post?sender=12335

###
# Get Post by ID
GET http://localhost:3000/post/674205c28c1b9b208115cc74

###
# Update Post
PUT http://localhost:3000/post/674205c28c1b9b208115cc74
Content-Type: application/json

{
  "content": "Updated Post content",
  "senderId": "UpdatedSender123"
}



