###


#create a comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "1234567890abcdef12345678",
  "content": "This is a new comment.",
  "senderId": "User12345"
}

###
#get all comments

GET http://localhost:3000/comments

###

#get comments by postId
GET http://localhost:3000/comments?postId=1234567890abcdef12345678

###

#update a comment
PUT http://localhost:3000/comments/6742160a095b0cada06a91cc
Content-Type: application/json

{
  "content": "Updated comment content"
}

###

# מחיקת תגובה
DELETE http://localhost:3000/comments/6742160a095b0cada06a91cc
